In [1]:
import pandas as pd
import re

In [2]:
# Prep data for attribute extraction
dataset_normalized_attributes = pd.read_excel('../Data/Normalized_product_attribute_name.xlsx', sheet_name = 'Normalized Product Attributes')
dataset_normalized_attributes

,BedType,OTA TYPE = BED,Unnamed: 2,RoomType,OTA TYPE = GRI,Unnamed: 5,Rateplan Incl/Value-adds,OTA TYPE = HAC,Unnamed: 8,Room Amenities,OTA TYPE = RMA,Unnamed: 11,Mealplan,OTA TYPE = MPT,Unnamed: 14,RoomView,OTA TYPE = RVT,Unnamed: 17,Taxes & Fees,OTA TYPE = FTT
0,Double/Full Bed,1.0,NaN,Accessible Room,1.0,NaN,Piano,0,NaN,Adjoining rooms,1.0,NaN,All Inclusive,1.0,NaN,Airport view,1.0,NaN,Bed tax,1.0
1,Futon Bed,2.0,NaN,Suite,3.0,NaN,24-hour front desk,1,NaN,Air conditioning,2.0,NaN,Full Board or American,2.0,NaN,Bay view,2.0,NaN,City hotel fee,2.0
2,King Bed,3.0,NaN,Executive/Club Suite,6.0,NaN,24-hour room service,2,NaN,Alarm clock,3.0,NaN,Buffet Breakfast,4.0,NaN,City view,3.0,NaN,PropertyFee,2.0
3,Murphy Bed,4.0,NaN,Double Room,10.0,NaN,24-hour security,3,NaN,All news channel,4.0,NaN,Continental Breakfast,6.0,NaN,Courtyard view,4.0,NaN,City tax,3.0
4,Queen Bed,5.0,NaN,King Bedroom,11.0,NaN,adjoining rooms,4,NaN,radio,5.0,NaN,Family Plan,9.0,NaN,Golf View,5.0,NaN,Municipal Tax,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,NaN,NaN,NaN,NaN,NaN,NaN,Train station shuttle services,2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,NaN,NaN,NaN,NaN,NaN,NaN,Electric car charging stations,2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,NaN,NaN,NaN,NaN,NaN,NaN,Golf clubs (equipments),2032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380,NaN,NaN,NaN,NaN,NaN,NaN,Beach club,2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,NaN,NaN,NaN,NaN,NaN,NaN,Theme park shuttle,2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:

room_types = dataset_normalized_attributes['RoomType'].dropna().unique()
room_types_list = room_types.tolist()

bed_types = dataset_normalized_attributes['BedType'].dropna().unique()
bed_types_list = bed_types.tolist()

room_amenities = dataset_normalized_attributes['Room Amenities'].dropna().unique()
room_amenities_list = room_amenities.tolist()

In [4]:
room_types_list

['Accessible Room ',
 'Suite',
 'Executive/Club Suite',
 'Double Room ',
 'King Bedroom',
 'Apartment',
 'Queen Bedroom',
 'Penthouse',
 'Studio Suite',
 'Twin Room',
 'Family Room/Suite',
 'Cabin',
 'Cottage',
 'Loft',
 'Guest Room',
 'Bungalow',
 'Villa',
 'Junior Suite',
 'Run of the House',
 'Large/Master Suite',
 'Executive/Club Room',
 'Classic Room',
 'Comfort Room',
 'Deluxe Room',
 'Deluxe Suite',
 'Economy Room',
 'Luxury Suite',
 'Premier Room',
 'Standard Guest Room',
 'Superior Room',
 'Superior Suite',
 'Grand Room',
 'Premier Suite',
 'Luxury Room',
 'Classic Suite',
 'Presidential Suite',
 'Single Room',
 'Triple Room',
 'Quadruple Room',
 'Studio Room',
 'Cabana',
 'Privilege Room',
 'Prestige Room',
 'Corner Room',
 'Signature Room',
 'Traditional Room ',
 'Wellness Room',
 'Terrace Room',
 'Tower Room',
 'Heritage Room',
 'Urban Room']

In [5]:
bed_types_list

['Double/Full Bed',
 'Futon Bed',
 'King Bed',
 'Murphy Bed',
 'Queen Bed',
 'Sofa Bed',
 'Twin/Single Bed',
 'Single Bed',
 'Run of the house',
 'Dorm/Bunk Bed',
 'Water Bed']

In [6]:
room_amenities_list

['Adjoining rooms',
 'Air conditioning',
 'Alarm clock',
 'All news channel',
 'radio',
 'Baby listening device',
 'balcony',
 'Barbeque grills',
 'Bathtub with spray jets',
 'Bathrobe',
 'Bathroom amenities',
 'Bathroom telephone',
 'Bathtub',
 'Bathtub only',
 'Bathtub & shower',
 'Bidet',
 'Bottled water',
 'Cable television',
 'Coffee maker',
 'Color television',
 'Computer',
 'Connecting rooms',
 'electric converters ',
 'Copier',
 'Cordless phone',
 'Cribs',
 'Data port',
 'Desk',
 'Desk with lamp',
 'Dining guide',
 'Direct dial phone number',
 'Dishwasher',
 'Double beds',
 'Dual voltage outlet',
 'Electrical current voltage',
 'Ergonomic chair',
 'Extended phone cord',
 'Fax machine',
 'Fire alarm',
 'Fire alarm with light',
 'Fireplace',
 'Free toll free calls',
 'Free calls',
 'Free credit card access calls',
 'Free local calls',
 'Free movies',
 'Full kitchen',
 'Grab bars in bathroom',
 'Grecian tub',
 'Hairdryer',
 'High speed internet connection',
 'Interactive web TV',
 'International direct dialing',
 'Internet access',
 'Iron',
 'Ironing board',
 'Whirlpool',
 'King bed',
 'Kitchen',
 'Kitchen supplies',
 'Kitchenette',
 'Knock light',
 'Laptop',
 'Large desk',
 'Large work area',
 'Laundry basket',
 'Loft',
 'Microwave',
 'Minibar',
 'Modem',
 'Modem jack',
 'Multi-line phone',
 'Newspaper',
 'Non-smoking',
 'Notepads',
 'Office supplies',
 'Oven',
 'Pay per view movies on TV',
 'Pens',
 'Phone in bathroom',
 'Plates and bowls',
 'Pots and pans',
 'Prayer mats',
 'Printer',
 'Private bathroom',
 'Queen bed',
 'Recliner',
 'Refrigerator',
 'Refrigerator with ice maker',
 'Remote control television',
 'Rollaway bed',
 'Safe',
 'Scanner',
 'Separate closet',
 'Separate modem line available',
 'Shoe polisher',
 'Shower only',
 'Silverware',
 'Sitting area',
 'Smoke detectors',
 'Smoking',
 'Sofa bed',
 'Speaker phone',
 'Stereo',
 'Stove',
 'Tape recorder',
 'Telephone',
 'Telephone for hearing impaired',
 'Telephones with message light',
 'Toaster oven',
 'Trouser press',
 'Turn down service',
 'Twin bed',
 'Vaulted ceilings',
 'VCR movies',
 'VCR player',
 'Video games',
 'Voice mail',
 'Wake-up calls',
 'Water closet',
 'Water purification system',
 'Wet bar',
 'Wireless internet connection',
 'Wireless keyboard',
 'Adaptor available for telephone PC use',
 'Air conditioning individually controlled in room',
 'Bathtub & whirlpool',
 'Telephone with data ports',
 'CD player',
 'Complimentary local calls time limit',
 'Extra person charge for rollaway use',
 'feather pillows',
 'Desk with electrical outlet',
 'ESPN available',
 'Foam pillows',
 'HBO available',
 'High ceilings',
 'Marble bathroom',
 'List of movie channels available',
 'Pets allowed',
 'Oversized bathtub',
 'Shower',
 'Sink in-room',
 'Soundproofed room',
 'Storage space',
 'Tables and chairs',
 'Two-line phone',
 'Walk-in closet',
 'Washer dryer',
 'Weight scale',
 'Welcome gift',
 'Spare electrical outlet available at desk',
 'Non refundable charge for pets',
 'Refundable deposit for pets',
 'Separate tub and shower',
 'Entrance type to guest room',
 'Ceiling fan',
 'CNN available',
 'Electrical adaptors available',
 'Buffet breakfast',
 'Accessible room',
 'Closets in room',
 'DVD player',
 'Mini refrigerator',
 'Separate line billing for multi-line phone',
 'Self-controlled heating/cooling system',
 'Toaster',
 'Analog data port',
 'Collect calls',
 'International calls',
 'Carrier access',
 'Interstate calls',
 'Intrastate calls',
 'Local calls',
 'Long distance calls',
 'Operator assisted calls',
 'Credit card access calls',
 'Calling card calls',
 'Toll free calls',
 'Universal adaptors',
 'Bathtub seat',
 'Canopy',
 'glassware',
 'Entertainment center',
 'Family room',
 'Hypoallergenic bed',
 'Hypoallergenic pillows',
 'Lamp',
 'Meal included - breakfast',
 'Meal included - continental breakfast',
 'Meal included - dinner',
 'Meal included - lunch',
 'Shared bathroom',
 'Textphone',
 'Water bed',
 'Extra adult charge',
 'Extra child charge',
 'Extra child charge for rollaway use',
 'Meal included: full American breakfast',
 'Futon',
 'Murphy bed',
 'Tatami mats',
 'Single bed',
 'Annex room',
 'Free newspaper',
 'Honeymoon suites',
 'Complimentary high speed internet in room',
 'Maid service',
 'PC hook-up in room',
 'Satellite television',
 'VIP rooms',
 'Cell phone recharger',
 'DVR player',
 'iPod docking station',
 'Media center',
 'Plug & play panel',
 'Satellite radio',
 'Video on demand',
 'Exterior corridors',
 'Gulf view',
 'Interior corridors',
 'Mountain view',
 'Ocean view',
 'High speed internet access for fee',
 'High speed wireless',
 'Premium movie channels',
 'Slippers',
 "First nighters' kit",
 'Chair provided with desk',
 'Pillow top mattress',
 'Feather bed',
 'Duvet',
 'Luxury linen type',
 'International channels',
 'Pantry',
 'Dish-cleaning supplies',
 'Double vanity',
 'Lighted makeup mirror',
 'Upgraded bathroom amenities',
 'VCR player available at front desk',
 'Instant hot water',
 'Outdoor space',
 'Hinoki tub',
 'Private pool',
 'High Definition (HD) Flat Panel Television - 32 inches or greater',
 'Room windows open',
 'Bedding type unknown or unspecified',
 'Full bed',
 'Round bed',
 'TV',
 'Child rollaway',
 'DVD player available at front desk',
 'Video game player:',
 'Video game player available at front desk',
 'Dining room seats',
 'Full size mirror',
 'Mobile/cellular phones',
 'Movies',
 'Multiple closets',
 'Plates/glassware',
 'Safe large enough to accommodate a laptop',
 'Bed linen thread count',
 'Blackout curtain',
 'Bluray player',
 'Device with mp3',
 'No adult channels or adult channel lock',
 'Non-allergenic room',
 'Pillow type',
 'Seating area with sofa/chair',
 'Separate toilet area',
 'Web enabled',
 'Widescreen TV',
 'Other data connection',
 'Phoneline billed separately',
 'Separate tub or shower',
 'Roof ventilator',
 "Children's playpen",
 'Plunge pool',
 'DVD movies',
 'Air filtration',
 'Exercise Equipment in Room',
 'Towels Sheets',
 'Electric Kettle',
 'Portable Fan',
 'Washing Machine',
 'Towels Provided',
 'Smart TV',
 'Streaming Services',
 'Highchair',
 'Toilet with electronic bidet',
 'Free tea bags instant coffee',
 'Outdoor Shower',
 'Baby bath',
 'Changing table',
 'Heating/Heated floor',
 'Indoor private mineral hot springs (japanese style onsen)',
 'Freezer',
 'Ice maker',
 'In room childcare',
 'Digital TV serviceWired Internet Access',
 'Wired Internet Access',
 'Pillow Menu',
 'Room Size(Square feet)',
 'Room Size (Square meters)',
 'Cleaning Supplies',
 'Dryer',
 'Tatami (Woven mat) floors',
 'Private spa tub',
 'Cookware, dishware, and utensils']

In [7]:
dataset = pd.read_csv('../Data/Product_Normalization_GRI_Expanded.csv')
dataset.head()

,Unnamed: 0,Room Description,Guest Room Info,Room Description Expanded
0,0,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...,Accessible Room,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...
1,1,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...
2,2,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...
3,3,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...,Accessible Room,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...
4,4,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...,Accessible Room,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...

In [8]:
sampled_descriptions = dataset.groupby('Guest Room Info').apply(
    lambda x: x['Room Description Expanded'].sample()
)

print(sampled_descriptions)

Guest Room Info
Accessible Room       380      STANDARD RATE ACCESSIBLE 2 QNQN TUB|ACCESSIBLE...
Apartment             32656     GLOBAL PROGRAM|TWO BEDROOM GARDEN VIEW APARTMENT
Bungalow              13090    GET REAL EXPERIENCE IT ALL|SIGNATURE BUNGALOW ...
Cabana                31871    CWT PROGRAM -SEMI FLEX|CABANA TERRACE FIRE PIT...
Classic Room          17907    PREFERRED BED AND BREAKFAST|CLASSIC ROOM - AVE...
Classic Suite         27819    GOVERNMENT RATE|CLASSIC SUITE  ONE BEDROOM KIN...
Comfort Room          18677    BAR ROOM ONLY INCLUDES FREE WI|COMFORT ROOM, 2...
Cottage               10164    MEMBER RETAIL RATE|MEMBER RATE FLEXIBLE, COTTA...
Deluxe Room           19071    TRIPADVISOR PLUS|OCEAN FRONT DELUXE KNG OR DOU...
Deluxe Suite          20103    FLEXIBLE RATE|DELUXE SUITE-1 KING-CITY VIEW-LE...
Double Bed            3082        CCS PUBLIC SECTOR RATE RO|SPACIOUS DOUBLE ROOM
Executive/Club Room   16750    AAA/CAA RATE|1 QUEEN BED EXECUTIVE ACCESSIBLE ...
Executive/Club Suite  2853     DISCOUNT|STAY LONGER AND SAVE, INCLUDES SEE RA...
Family Room/Suite     9104     WHERE NEXT|FAMILY ROOM 431 SQFT 40 SQM FREE WI...
Guest Room            12693    STAY PASS|WORK ANYWHERE STAY PASS, SEE RATE DE...
Junior Suite          15713    PREPAY REFUNDABLE|PREPAY REFUNDABLE, CHANGES U...
King Bedroom          4785     CWT PROGRAM -SEMI FLEX|SPA KING ROOM NONSMOKIN...
Loft                  11114    MEMBER RATE 5TH AVE TERR SUITE|1 KING:694SF:LO...
Luxury Room           26184    GOVERNMENT RATE|EMPLOYEE ID REQUIRED AT CHECK ...
Luxury Suite          33028    BED AND BREAKFAST|1 BEDROOM LUXURY SUITE KING-...
Penthouse             6580     SAVE ON 2-3 NIGHTS|PENTHOUSE SUITE 2 BEDROOM  ...
Premier Room          21089    FLEXIBLE RATE|PREMIUM ROOM - 2 DOUBLE BEDS MOB...
Premier Suite         25770    FLEXIBLE RATE|2 ROOM PREMIUM SUITE - 1 KING BE...
Presidential Suite    28232    SEMI-FLEX|PRESIDENTIAL SUITE ONE BEDROOM 1 KIN...
Queen Bedroom         5347     SEMI-FLEX|QUEEN ROOM HDTV/FREE WI-FI/HOT BREAK...
Run of the House      34155    BEST FLEXIBLE RATE|SPECIALTY ROOM WHEN YOU ARR...
Single Room           29374           PREPAID - LEVEL 01 WITH BREAKF|SINGLE ROOM
Standard Room         22176    STANDARD PLAN.STANDARD|STANDARD ROOM: JAPANESE...
Studio Room           30717    2X POINTS PACKAGE|2 QUEEN BEDS STUDIO NONSMOKI...
Studio Suite          7794     VIRTUOSO|GRAND GARDEN STUDIO 75 SQM WITH A FUR...
Suite                 1452     JP MORGAN CHASE -PREFERRED RAT|1 KING BED WITH...
Superior Room         23200    MRATE AVAIL FLEXIBLE RATE|SUPERIOR ROOM WITH 1...
Superior Suite        24475    TRAVEL YOUR WAY SUITE SAVE 20|SUPERIOR SUITE-O...
Twin Room             8311     AP BREAKFAST INCLUDE|TWIN ROOM COMP WIFI/MINI ...
Villa                 14324    BEST AVAILABLE RATE BREAKFAST|SHIKUMEN VILLA T...
Name: Room Description Expanded, dtype: object

/var/folders/4s/6q_4fv2n6g94291jrzmhdsch0000gn/T/ipykernel_35515/120762231.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_descriptions = dataset.groupby('Guest Room Info').apply(

In [9]:
#%%
# Count occurrences of ' bed ' (case insensitive, with word boundaries)
bed_counts = dataset['Room Description Expanded'].str.count(r'\b bed \b', flags=re.IGNORECASE)

print(f"Total occurrences of 'bed': {bed_counts.sum()}")
print(f"Total Descriptions: {len(dataset)}")

Total occurrences of 'bed': 6239
Total Descriptions: 35000

In [10]:
#%%
# Count occurrences of ' bed room ' (case insensitive, with word boundaries)
bed_room_counts = dataset['Room Description Expanded'].str.count(r'\b bed room \b', flags=re.IGNORECASE)

print(f"Total occurrences of ' bed room ': {bed_room_counts.sum()}")
print(f"Total Descriptions: {len(dataset)}")

Total occurrences of ' bed room ': 97
Total Descriptions: 35000

In [11]:
#%%
# Count occurrences of ' bed room ' (case insensitive, with word boundaries)
bed_room_counts = dataset['Room Description Expanded'].str.count(r'\b bedroom \b', flags=re.IGNORECASE)

print(f"Total occurrences of ' bed room ': {bed_room_counts.sum()}")
print(f"Total Descriptions: {len(dataset)}")

Total occurrences of ' bed room ': 3844
Total Descriptions: 35000